# Generated by Django 5.2.6 on 2025-09-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_thumbnail_url_product_thumbnail_and_more'),
    ]

    operations = [
    ]
